name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  node:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20']

    name: node${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint
